### ISSUE TITLE
InfoQ

### ISSUE THREAD

**Issue by synodinos** [philipkiely/whopaystechnicalwriters#173]
Company name: InfoQ
Link: https://www.infoq.com/write-for-infoq/
Pay rate: Quarterly revenue share

Editor/contact email: https://www.infoq.com/write-for-infoq/
Topics: Development, Architecture & Design, AL/ML, Data Engineering, DevOps
Notes: InfoQ is written exclusively by software practitioners like yourself. Our goal is to share inspiring content from real-world use cases, best practices used by innovator and early adopter companies, and news on emerging trends.

**Comment by philipkiely** [comment]
Got it, thanks!
