### ISSUE TITLE
Update status for Webiny CMS

### ISSUE THREAD

**Issue by kumar-kalyan** [philipkiely/whopaystechnicalwriters#175]
Company name: Webiny CMS
Link: https://www.webiny.com/forms/write-with-webiny
Status: Temporarily closed to new writers
![Webiny](https://github.com/philipkiely/whopaystechnicalwriters/assets/67071462/5608abdb-d804-4a94-936e-7607650608ef)

@philipkiely

**Comment by philipkiely** [comment]
Ty, updated!
