### ISSUE TITLE
Add Frontend Masters' Boost

### ISSUE THREAD

**Issue by Pinjasaur** [philipkiely/whopaystechnicalwriters#176]
URL: https://frontendmasters.com/blog/guest-writing-for-boost/

Frontend Masters' has recently been promoting their publication Boost: https://frontendmasters.com/blog/. This includes [Chris Coyier](https://chriscoyier.net/2024/01/02/boost/) so it seems like it might be the logical sequel to CSS-Tricks since their guest writing program is still closed: https://css-tricks.com/guest-writing-for-css-tricks/

They don't have exact pay listed but I'll reach out over email, guessing this page is fresh so they're still finalizing what their budget for contributions looks like. If I hear back I'll update this issue or make a new one accordingly.

Thanks @philipkiely for continuing to maintain this. :)

**Comment by chriscoyier** [comment]
Hey I got an email from @Pinjasaur about this.

Budget is $300 generally. 

I'd say it's a bit of a sliding scale as there is opportunity for short-form stuff. We'd have to talk it through but lower cost-per-article, higher volume, probably series-based stuff. Or, if there is a great idea that requires more research, planning, or coding/demo-creation, it's possible we can go up from there. Best idea: just reach out! Let's talk!

**Comment by philipkiely** [comment]
Hi Paul & Chris,

Thanks for bringing this to my attention! I'll get this added to the site and feature it in the February newsletter.

Chris — awesome to see a new publication from you!
