### ISSUE TITLE
Proposed Addition: Mattermost

### ISSUE THREAD

**Issue by philipkiely** [philipkiely/whopaystechnicalwriters#31]
{"name":"Mattermost","type":"publication","link":"https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/community-content-program","topics":["DevOps"," Full-stack Development"," Frameworks & Libraries"," Productivity Tips"],"minRate":250,"maxRate":350}

**Comment by Pinjasaur** [comment]
I submitted this one. Slick use of GH btw.

Small detail, $250-350 USD is the _normal_ rate but their docs mention $500 USD for "exceptionally detailed content about prevalent technologies." https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/community-content-program#compensation

**Comment by philipkiely** [comment]
Appreciate it! I'll get this added in today's batch
