### ISSUE TITLE
Proposed Addition: NimbleBox.ai

### ISSUE THREAD

**Issue by philipkiely** [philipkiely/whopaystechnicalwriters#57]
{"name":"NimbleBox.ai","type":"publisher","link":"https://nimblebox.ai/technical-writer-program","contact":"rugman@nimblebox.ai","topics":["Machine Learning"," Data Science"," MLOps"],"royaltyRate":"50","notes":"Great recognition & editors give great feedback!"}

**Comment by rugmanasokan** [comment]
Hey Philip! We increase the compensation for our writer program to $100. 
Can you please change the content in the website.
