### ISSUE TITLE
Proposed Addition: Turnkey Labs

### ISSUE THREAD

**Issue by philipkiely** [philipkiely/whopaystechnicalwriters#62]
{"name":"Turnkey Labs","type":"publication","link":"https://turnkey-labs.com/tech-trends/","contact":"alex.p@turnkey-labs.com","topics":["Tech Trends and Software Development"],"minRate":100,"maxRate":200,"notes":"need english (us) native editing and proofreading"}

**Comment by Tonie-NG** [comment]
Still open? @philipkiely

**Comment by ped4enko** [comment]
no, remove please

**Comment by ped4enko** [comment]
@philipkiely I will be grateful

**Comment by philipkiely** [comment]
@ped4enko Removed.

**Comment by ped4enko** [comment]
thanks
